version: "3"
services:
  kode:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD: 'local'
    image: jdecode/slim-php:0.1
    ports:
      - 17229:80
    volumes:
      - .:/var/www/html
    environment:
      SENTRY_DSN: https://<some-long-uuid>@<some-small-number>.ingest.sentry.io/<some-number>
    networks:
      testing_net:
        ipv4_address: 172.29.1.1

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
