name: phpunit tests against locally Dockerised DynamoDB endpoint

on: [push]

jobs:
#  db-setup:
#    container:
#      image: docker://amazon/dynamodb-local:latest
#      ports:
#        - 8000:8000
#      options: --rm -d
#      steps:
#        - run: ls -al
#
  build:
#    needs: db-setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md
      - uses: docker://amazon/dynamodb-local:latest
      - name: Run local dynamo-db
        run: docker run --rm -d -p 8000:8000/tcp amazon/dynamodb-local:latest

      - name: Run test suite
        run: composer run tests
