name: phpunit tests against locally Dockerised DynamoDB endpoint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazon/dynamodb-local:latest
      ports: 8000:8000

    steps:
      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        run: composer run tests
